### ISSUE TITLE
Что за гамма коррекция такая?

### ISSUE THREAD

**Issue by qywx** [Silencer2K/stm32f10x-ws2812b-lib#2]
`#define WS2812B_USE_GAMMA_CORRECTION` какова функциональность, как это на цвета влияет?

**Comment by silencer2k** [comment]
https://en.wikipedia.org/wiki/Gamma_correction
https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%BC%D0%BC%D0%B0-%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D0%BA%D1%86%D0%B8%D1%8F

Коррекция зависимости яркости светодиода (видимой яркости) от отправляемого в него значения яркости (raw value). В библиотеке по-умолчанию используется: raw value = ((value / 255) ^ 2) \* 255 - это обеспечивает линейную зависимость яркости (видимой яркости) от подаваемого на вход библиотечных функций значений R, G, B (для RGB) и V (для HSV).

Более подробно: http://fizzible.com/led-tricks-gamma-correction/
